In [14]:
import numpy as np
import random
from collections import deque

In [23]:
class PuzzleGame:
    def __init__(self):
        self.desired_result = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 0]])
        self.board = self.desired_result.copy()
        self.shuffle()

    def shuffle(self):
        flat_solution = self.desired_result.flatten()
        flat_board = flat_solution.copy()
        while True:
            np.random.shuffle(flat_board)
            if self.is_solvable(flat_board):
                break
        self.board = np.array(flat_board).reshape((3, 3))

    def is_solvable(self, board):
        inversions = 0
        for i in range(len(board)):
            for j in range(i + 1, len(board)):
                if board[i] > board[j] and board[i] != 0 and board[j] != 0:
                    inversions += 1
        return inversions % 2 == 0

    def display_board(self):
        print(self.board)

    def is_solved(self):
        return np.array_equal(self.board, self.desired_result)

    def get_neighbors(self):
        neighbors = []
        zero_position = np.argwhere(self.board == 0)[0]
        moves = [(0, 1), (0, -1), (1, 0), (-1, 0)]
        for move in moves:
            new_pos = tuple(zero_position + move)
            if 0 <= new_pos[0] < 3 and 0 <= new_pos[1] < 3:
                new_board = self.board.copy()
                new_board[zero_position[0], zero_position[1]], new_board[new_pos[0], new_pos[1]] = new_board[new_pos[0], new_pos[1]], new_board[zero_position[0], zero_position[1]]
                neighbors.append(new_board)
        return neighbors

    def iterative_deepening_search(self, max_depth=15):
        for depth in range(max_depth):
            path = self.depth_limited_search(self.board, depth)
            if path is not None:
                return path
        return None

    def depth_limited_search(self, state, depth_limit):
        return self.recursive_dls(state, depth_limit)

    def recursive_dls(self, state, depth_limit):
        if np.array_equal(state, self.desired_result):
            return [state]

        if depth_limit == 0:
            return None

        for neighbor in self.get_neighbors():
            result = self.recursive_dls(neighbor, depth_limit - 1)
            if result is not None:
                result.insert(0, state)
                return result
        return None


Game = PuzzleGame()
print("Initial Board:")
Game.display_board()

path = Game.iterative_deepening_search()
if path is not None:
    print("Solution found:")
    for state in path:
        print(state)
else:
    print("No solution found within depth limit.")


Initial Board:
[[3 5 1]
 [0 6 2]
 [7 4 8]]
No solution found within depth limit.
