In [6]:
import numpy as np
import random
from collections import deque

In [8]:
class PuzzleGame:
    def __init__(self):
        self.solution = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 0]])
        self.board = self.solution.copy()
        self.shuffle()

    def shuffle(self):
        flat_solution = self.solution.flatten()
        flat_board = flat_solution.copy()
        while True:
            np.random.shuffle(flat_board)
            if self.is_solvable(flat_board):
                break
        self.board = np.array(flat_board).reshape((3, 3))

    def is_solvable(self, board):
        inversions = 0
        for i in range(len(board)):
            for j in range(i+1, len(board)):
                if board[i] > board[j] and board[i] != 0 and board[j] != 0:
                    inversions += 1
        return inversions % 2 == 0

    def display_board(self):
        for row in self.board:
            print(' '.join(map(str, row)))

    def is_solved(self):
        return np.array_equal(self.board, self.solution)

    def solve_bfs(self):
        queue = deque([(self.board, [])])
        visited = set()
        while queue:
            current_board, path = queue.popleft()
            if np.array_equal(current_board, self.solution):
                return path
            zero_pos = np.argwhere(current_board == 0)[0]
            for neighbor in self.get_neighbors(zero_pos):
                new_board = current_board.copy()
                new_board[zero_pos[0], zero_pos[1]], new_board[neighbor[0], neighbor[1]] = new_board[neighbor[0], neighbor[1]], new_board[zero_pos[0], zero_pos[1]]
                if tuple(map(tuple, new_board)) not in visited:
                    queue.append((new_board, path + [tuple(map(tuple, new_board))]))
                    visited.add(tuple(map(tuple, new_board)))
        return None

    def get_neighbors(self, pos):
        neighbors = []
        moves = [(0, 1), (0, -1), (1, 0), (-1, 0)]
        for move in moves:
            new_pos = pos + move
            if 0 <= new_pos[0] < 3 and 0 <= new_pos[1] < 3:
                neighbors.append(new_pos)
        return neighbors

game = PuzzleGame()
print("Initial Board:")
game.display_board()
solution = game.solve_bfs()
if solution:
    for i, step in enumerate(solution):
        print(f"Step {i+1}:")
        print(np.array(step))
        
    print(f"Solution found in {len(solution)} moves.")
else:
    print("No solution found.")


Initial Board:
2 6 8
4 3 7
5 1 0
Step 1:
[[2 6 8]
 [4 3 0]
 [5 1 7]]
Step 2:
[[2 6 0]
 [4 3 8]
 [5 1 7]]
Step 3:
[[2 0 6]
 [4 3 8]
 [5 1 7]]
Step 4:
[[2 3 6]
 [4 0 8]
 [5 1 7]]
Step 5:
[[2 3 6]
 [4 1 8]
 [5 0 7]]
Step 6:
[[2 3 6]
 [4 1 8]
 [0 5 7]]
Step 7:
[[2 3 6]
 [0 1 8]
 [4 5 7]]
Step 8:
[[2 3 6]
 [1 0 8]
 [4 5 7]]
Step 9:
[[2 3 6]
 [1 5 8]
 [4 0 7]]
Step 10:
[[2 3 6]
 [1 5 8]
 [4 7 0]]
Step 11:
[[2 3 6]
 [1 5 0]
 [4 7 8]]
Step 12:
[[2 3 0]
 [1 5 6]
 [4 7 8]]
Step 13:
[[2 0 3]
 [1 5 6]
 [4 7 8]]
Step 14:
[[0 2 3]
 [1 5 6]
 [4 7 8]]
Step 15:
[[1 2 3]
 [0 5 6]
 [4 7 8]]
Step 16:
[[1 2 3]
 [4 5 6]
 [0 7 8]]
Step 17:
[[1 2 3]
 [4 5 6]
 [7 0 8]]
Step 18:
[[1 2 3]
 [4 5 6]
 [7 8 0]]
Solution found in 18 moves.
