### Tuple, Dictionary , Class, numpy, lamda function


1. Create Python Lists

In [2]:
# --list of floats
areas = [10.0, 16.0, 10.0]
print(areas)

[10.0, 16.0, 10.0]


In [3]:
# --list with mixed data types
areas = ["hall", 10.0, "bath" , 16.0 , "bed", 10.0]
print(areas)

['hall', 10.0, 'bath', 16.0, 'bed', 10.0]


In [4]:
# --nested list
# a. list as an item 

garage_area = [11.0,12.0]
areas = ["hall", 10.0, "bath" , 16.0 , "bed", 10.0 , garage_area]
print(areas)

['hall', 10.0, 'bath', 16.0, 'bed', 10.0, [11.0, 12.0]]


In [5]:
# b. list of lists

bedroom_area = [11.0 , 12.0]
hallway_area = [13.0 , 15.0]
pool_area = [16.0 , 19.0 , 12.0]

areas = [bedroom_area , hallway_area , pool_area]
print(areas)

[[11.0, 12.0], [13.0, 15.0], [16.0, 19.0, 12.0]]


2. Access List Elements

In [6]:
# -- List index
numbers = [0, 1, 2, 3, 4, 5, 6, 7]

print(numbers[0])

0


In [7]:
# -- Nested List indexing

numbers2d = [[0,1],[2,3],[3,5]]

print(numbers2d[0][0])

0


In [8]:
# -- Negative indexing
print(numbers[-5])

3


In [16]:
#----2. List Slicing Elements ----

print(numbers[2:6])

print(numbers[3:])

print(numbers[:])



[2, 3, 4, 5]
[3, 4, 5, 6, 7]
[0, 1, 2, 3, 4, 5, 6, 7]


3. Mutable Lists

In [17]:

even = [3 , 5 , 7 , 11]

even[0] = 0

even[1:] = [2,4,8]

print(even)

[0, 2, 4, 8]


4. Concatenating and repeating lists

In [9]:
odd = [1, 3, 5]

print(odd + [9, 7, 5])

print(["re"] * 3)

[1, 3, 5, 9, 7, 5]
['re', 're', 're']


5. List Methods 

In [11]:
even = [3 , 5 , 7 , 11]

# append() 1 item
even.append(12)
even.append([14,16]) #will be added as list

print(even)

[3, 5, 7, 11, 12, [14, 16]]


In [10]:
# extend() add more items
# even.append([14,16,18])
even.extend([14,16,18])
print(even)

#insert() 1 or more at a position
odd = [1, 9]
odd.insert(1,3)

print(odd)

#odd[2:2] = [5, 7]

[3, 5, 7, 11, 12, [14, 16]]
[3, 5, 7, 11, 12, [14, 16], 14, 16, 18]
[1, 3, 9]


Tuple

In [1]:
# Different types of tuples

#  --Empty tuple
my_tuple = ()
print(my_tuple)

()


In [2]:
# -- Tuple having integers
my_tuple = (1, 2, 3)
print(my_tuple)

(1, 2, 3)


In [3]:
# -- tuple with mixed datatypes
my_tuple = (1, "Hello", 3.4)
print(my_tuple)

(1, 'Hello', 3.4)


In [4]:
# -- nested tuple
my_tuple = ("mouse", [8, 4, 6], (1, 2, 3))
print(my_tuple)

('mouse', [8, 4, 6], (1, 2, 3))


In [5]:
# -- one element tupple ? Possible ?

my_tuple = ("hello")
print(type(my_tuple))  # <class 'str'>

<class 'str'>


In [6]:
# Creating a tuple having one element
my_tuple = ("hello",)
print(type(my_tuple))  # <class 'tuple'>

<class 'tuple'>


In [7]:
# Parentheses is optional
my_tuple = "hello",
print(type(my_tuple))  # <class 'tuple'>

#NOPE!



<class 'tuple'>


2. Tuple packing and unpacking

In [8]:
#The process of assigning values to a tuple is known as packing.

#A tuple can also be created without using parentheses
my_tuple = 3, 4.6, "dog",1
print(my_tuple)

# tuple unpacking is also possible
a, b, c,d = my_tuple

print(a)      # 3
print(b)      # 4.6
print(c)      # dog
print(d)      # 1

(3, 4.6, 'dog', 1)
3
4.6
dog
1


3. Access Tuple Elements

In [13]:
# -- Indexing
my_tuple = ('p','e','r','m','i','t')
print(my_tuple[0])   # 'p' 
print(my_tuple[5])   # 't'

p
t


In [15]:
# IndexError: list index out of range
#print(my_tuple[6])

In [20]:
# -- Index must be an integer
# TypeError: list indices must be integers, not float
# my_tuple[2.0]

In [17]:
# -- nested tuple
n_tuple = ("mouse", [8, 4, 6], (1, 2, 3))

print(n_tuple[0][3])       # 's'
print(n_tuple[1][1])       # 4

s
4


In [21]:
# -- Negative Indexing
my_tuple = ('p', 'e', 'r', 'm', 'i', 't')


print(my_tuple[-1])


print(my_tuple[-6])


t
p


4. Slicing

In [22]:
# Accessing tuple elements using slicing
my_tuple = ('p','r','o','g','r','a','m','i','z')

# elements 2nd to 4th
# Output: ('r', 'o', 'g')
print(my_tuple[1:4])

('r', 'o', 'g')


In [6]:
# --- 5. Mutable Tupple

# Changing tuple values
my_tuple = (4, 2, 3, [6, 5])

# TypeError: 'tuple' object does not support item assignment
my_tuple[1] = 9

TypeError: 'tuple' object does not support item assignment

In [7]:

# However, item of mutable element can be changed
my_tuple[3][1] = 9    # Output: (4, 2, 3, [9, 5])
print(my_tuple)

# Tuples can be reassigned
my_tuple = ('p', 'r', 'o', 'g', 'r', 'a', 'm', 'i', 'z')

# Output: ('p', 'r', 'o', 'g', 'r', 'a', 'm', 'i', 'z')
print(my_tuple)

(4, 2, 3, [6, 9])
('p', 'r', 'o', 'g', 'r', 'a', 'm', 'i', 'z')


In [25]:
# --- 6. Operations on Tupples
# Concatenation
# Output: (1, 2, 3, 4, 5, 6)
print((1, 2, 3) + (4, 5, 6))

# Repeat
# Output: ('Repeat', 'Repeat', 'Repeat')
print(("Repeat",) * 3)

(1, 2, 3, 4, 5, 6)
('Repeat', 'Repeat', 'Repeat')


In [ ]:
# ---- 7 .Deleting a Tupple
# Deleting tuples
my_tuple = ('p', 'r', 'o', 'g', 'r', 'a', 'm', 'i', 'z')

# can't delete items
# TypeError: 'tuple' object doesn't support item deletion
# del my_tuple[3]

# Can delete an entire tuple
del my_tuple

# NameError: name 'my_tuple' is not defined
print(my_tuple)

In [ ]:
#--------------------------------#
#        LIST VS TUPPLE          #
#--------------------------------#

# list mutable 
# tupple not 
# perf : tupple > list

#Since tuples are immutable, iterating through a tuple is faster than with list. So there is a slight performance boost.
#Tuples that contain immutable elements can be used as a key for a dictionary. With lists, this is not possible.


#No better option..depends upin usage

 ## Dictionary 

In [12]:
# 1 . Creating Python Dictionary

In [8]:
# -- empty dictionary
my_dict = {}


In [9]:
# -- dictionary with integer keys
my_dict = {1: 'apple', 2: 'ball'}

In [10]:
# -- dictionary with mixed keys
my_dict = {'name': 'John', 1: [2, 4, 3]}

In [11]:

# -- using dict()
my_dict = dict({1:'apple', 2:'ball'})

In [13]:
# -- from sequence having each item as a pair
my_dict = dict([(1,[(1,'apple'), (2,'ball')]), (2,'ball')])
print(my_dict[1][1])

#As you can see from above, we can also create a dictionary using the built-in dict() function.

(2, 'ball')


2 .Accessing Elements from Dictionary

In [ ]:

# get vs [] for retrieving elements
my_dict = {'name': 'Jack', 'age': 26}

# Output: Jack
print(my_dict['name'])

# Output: 26
print(my_dict.get('age'))

# Trying to access keys which doesn't exist throws error
# Output None
print(my_dict.get('address'))

# KeyError
print(my_dict['address'])

In [36]:
# ---3. Changing and Adding Dictionary elements
# Changing and adding Dictionary Elements
my_dict = {'name': 'Jack', 'age': 26}


In [37]:
# update value
my_dict['age'] = 27

#Output: {'age': 27, 'name': 'Jack'}
print(my_dict)


{'name': 'Jack', 'age': 27}


In [38]:
# add item
my_dict['address'] = 'Downtown'

# Output: {'address': 'Downtown', 'age': 27, 'name': 'Jack'}
print(my_dict)

{'name': 'Jack', 'age': 27, 'address': 'Downtown'}


In [39]:
# ---4. Removing elements from Dictionary
# Removing elements from a dictionary

# create a dictionary
squares = {1: 1, 2: 4, 3: 9, 4: 16, 5: 25}

# remove a particular item, returns its value
# Output: 16
print(squares.pop(4))

16


In [29]:
# Output: {1: 1, 2: 4, 3: 9, 5: 25}
print(squares)

{1: 1, 2: 4, 3: 9, 5: 25}


In [40]:
# remove an arbitrary item, return (key,value)
# Output: (5, 25)
print(squares.popitem())

(5, 25)


In [41]:
# Output: {1: 1, 2: 4, 3: 9}
print(squares)

# remove all items
squares.clear()

# Output: {}
print(squares)


{1: 1, 2: 4, 3: 9}
{}


In [42]:

# delete the dictionary itself
del squares



Lambda Functions

In [14]:
# simple function
def add(a):
  return a + 10

add(5)

15

A lambda function is a small anonymous function.

A lambda function can take any number of arguments, but can only have one expression.

In [15]:
x = lambda a : a + 10
x(5)

15

In [16]:
x = lambda a, b : a * b
x(5, 6)

30

Python Class

In [17]:
class Person:
  def __init__(self, name, age):
    self.name = name
    self.age = age

  def print_name(self):
    print(self.name)

In [18]:
p1 = Person("ali", 25)

print(p1.name)
print(p1.age)
p1.print_name()

ali
25
ali


The `numpy` package (module) is used in almost all numerical computation using Python. It is a package that provide high-performance vector, matrix and higher-dimensional data structures for Python. It is implemented in C and Fortran so when calculations are vectorized (formulated with vectors and matrices), performance is very good. 

To use `numpy` you need to import the module, using for example:

In [19]:
import numpy as np

## Creating `numpy` arrays

In [20]:
# a vector: the argument to the array function is a Python list
v = np.array([1,2,3,4])

v

array([1, 2, 3, 4])

In [21]:
# a matrix: the argument to the array function is a nested Python list
M = np.array([[1, 2], [3.0,4]])

M

array([[1., 2.],
       [3., 4.]])

The `v` and `M` objects are both of the type `ndarray` that the `numpy` module provides.

In [22]:
type(v), type(M)

(numpy.ndarray, numpy.ndarray)

The difference between the `v` and `M` arrays is only their shapes. We can get information about the shape of an array by using the `ndarray.shape` property.

In [23]:
v.shape

(4,)

In [24]:
M.shape

(2, 2)

The number of elements in the array is available through the `ndarray.size` property:

In [25]:
M.size

4

Equivalently, we could use the function `numpy.shape` and `numpy.size`

In [26]:
np.shape(M)

(2, 2)

In [27]:
np.size(M)

4

In [43]:
# a diagonal matrix
np.diag([1,2,3,5])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 5]])

In [44]:
# diagonal with offset from the main diagonal
np.diag([1,2,3], k=3) 

array([[0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 2, 0],
       [0, 0, 0, 0, 0, 3],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [45]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [46]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])