# Lab Task 01

Write a function to return True if the first and last number of a given list is same. If numbers are different then return False.

In [2]:
# Given:
numbers_x = [10, 20, 30, 40, 10]
numbers_y = [75, 65, 35, 75, 30]

# Function to check if the first and last number of a given list is same
def check_first_last(nums):
    if len(nums) > 1:
        return nums[0] == nums[-1]
    else:
        return True

# Test cases
print(check_first_last(numbers_x))
print(check_first_last(numbers_y))
print(check_first_last([1, 2, 3, 1]))
print(check_first_last([1, 2, 3]))
print(check_first_last([5]))

True
False
True
False
True






# Lab Task 02

Create two NumPy arrays of the same shape and perform element-wise addition on them.

Calculate the element-wise product of two NumPy arrays.

In [3]:
import numpy as np

# Creating two NumPy arrays of the same shape
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])

# Performing element-wise addition
result_add = arr1 + arr2
print("Element-wise addition:\n", result_add)

# Performing element-wise product
result_product = arr1 * arr2
print("Element-wise product:\n", result_product)

Element-wise addition:
 [[ 8 10 12]
 [14 16 18]]
Element-wise product:
 [[ 7 16 27]
 [40 55 72]]


# Lab Task 03

Reshape a 1D NumPy array into a 2D array with dimensions (3, 4).

Concatenate two NumPy arrays horizontally and vertically.

In [4]:
import numpy as np

# Creating a 1D array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

# Reshaping the array into (3, 4) dimensions
reshaped_arr = arr.reshape(3, 4)
print("Reshaped array:\n", reshaped_arr)

# Creating two NumPy arrays
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])

# Concatenating arrays horizontally
horizontal_concat = np.concatenate((arr1, arr2), axis=1)
print("Horizontal concatenation:\n", horizontal_concat)

# Concatenating arrays vertically
vertical_concat = np.concatenate((arr1, arr2), axis=0)
print("Vertical concatenation:\n", vertical_concat)

Reshaped array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Horizontal concatenation:
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
Vertical concatenation:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


# Lab Task 04




## Online Store Shopping Cart
Write a Python program to simulate the online store's shopping cart system. The program should use a while loop to provide an interactive shopping experience.


### Tasks:
* Initialize an empty list called shopping_cart to store items.
* Display a welcome message and available products.
* Loop should be iterating over AI Response Simulator and Investment decision and keep asking for user input.
* Prompt the user to enter the number corresponding to the product they want to add to the cart.
* Check if the user entered 'q'. If so, break the loop.
* Convert the choice to an integer and validate it within the valid range (1 to 3).
* Based on the user's choice, add the selected product to the shopping_cart list.
* Display a confirmation message indicating the added product.
* Continue the loop to allow the user to add more products or proceed to checkout.
* After the loop ends, display the contents of the shopping cart.
* Display a goodbye message.
* End the program.


In [1]:
# Initializing an empty list for the shopping cart
shopping_cart = []

# Defining available products and their prices
products = {
    1: {"name": "Shirt", "price": 20},
    2: {"name": "Hat", "price": 15},
    3: {"name": "Mug", "price": 10},
}

# Welcome message and product display
print("Welcome to the shopping cart program!")
for product_id, product_info in products.items():
    print(f"{product_id}. {product_info['name']} - ${product_info['price']}")

# Loop for adding items to the cart
while True:
    # Prompting for user input
    choice = input("\nEnter the number of the product you want to add (or 'q' to quit): ")

    # Checking if user wants to quit
    if choice.lower() == 'q':
        break

    # Validating user input
    try:
        choice = int(choice)
        if choice not in products:
            print("Invalid choice. Please choose a number between 1 and 3.")
            continue
    except ValueError:
        print("Invalid input. Please enter a number or 'q'.")
        continue

    # Adding product to cart and display confirmation
    product_info = products[choice]
    shopping_cart.append(product_info)
    print(f"{product_info['name']} has been added to your cart!")

# Displaying cart contents
print("\nYour shopping cart:")
for product_info in shopping_cart:
    print(f"- {product_info['name']} - ${product_info['price']}")

# Goodbye message
print("\nThank you for shopping! See you again soon.")

Welcome to the shopping cart program!
1. Shirt - $20
2. Hat - $15
3. Mug - $10

Enter the number of the product you want to add (or 'q' to quit): 2
Hat has been added to your cart!

Enter the number of the product you want to add (or 'q' to quit): 3
Mug has been added to your cart!

Enter the number of the product you want to add (or 'q' to quit): q

Your shopping cart:
- Hat - $15
- Mug - $10

Thank you for shopping! See you again soon.


# Lab Task 05


## Email Classification
Develope a tool which will classify an email.

### Tasks:
* Create a function classify_emails that takes a list of emails as an argument.
* Inside the function, categorize emails into "Important," "Promotions," and "Spam" based on keywords and content analysis.
* Loop through the emails and identify keywords to determine their category.
* If an email contains keywords indicating importance, assign it as "Important."
* If an email contains keywords related to promotions or deals, assign it as "Promotions."
* If an email is suspected to be spam based on certain keywords or patterns, assign it as "Spam."
* Return three lists of emails for each category.
* Print the lists.

In [7]:
def classify_emails(emails):
    important_emails = []
    promotional_emails = []
    spam_emails = []

    for email in emails:
        # Basic keyword matching
        if "urgent" in email.lower() or "important" in email.lower() or "meeting" in email.lower():
            important_emails.append(email)
        elif "sale" in email.lower() or "discount" in email.lower() or "promotion" in email.lower():
            promotional_emails.append(email)
        elif "unsubscribe" in email.lower() or "free trial" in email.lower() or "guarantee" in email.lower():
            spam_emails.append(email)
        else:
          # Add to default category (assuming Other)
          pass

    return important_emails, promotional_emails, spam_emails

# Example usage
emails = ["Meeting reminder: Project X", "50% off winter sale!", "Free trial: Unlimited access to music"]
important_emails, promotional_emails, spam_emails = classify_emails(emails)

print("Important emails:")
for email in important_emails:
    print("- " + email)

print("\nPromotional emails:")
for email in promotional_emails:
    print("- " + email)

print("\nSpam emails:")
for email in spam_emails:
    print("- " + email)

Important emails:
- Meeting reminder: Project X

Promotional emails:
- 50% off winter sale!

Spam emails:
- Free trial: Unlimited access to music


# Lab Task 06

## English-Spanish Dictionary
You are creating a basic English-Spanish dictionary that allows users to look up English words and find their Spanish translations.


### Tasks
* Create a dictionary where English words are keys and their Spanish translations are values.
* Ask the user to input an English word.
* Check if the word exists in the dictionary.
* If the word exists, print its Spanish translation.
* If the word does not exist, inform the user that the translation is not available.
* Implement a loop that allows the user to keep looking up words until they choose to exit.


In [2]:
# Creating a dictionary of English words and their Spanish translations
spanish_dictionary = {
    "hello": "hola",
    "goodbye": "adiós",
    "computer": "ordenador",
    "water": "agua",
    "book": "libro"
}

# Loop to keep looking up words until the user exits
while True:
    # Asking the user for an English word
    english_word = input("Enter an English word (or 'q' to quit): ").lower()

    # Checking if the word exists in the dictionary
    if english_word in spanish_dictionary:
        # Printing the Spanish translation
        spanish_translation = spanish_dictionary[english_word]
        print(f"The Spanish translation of '{english_word}' is '{spanish_translation}'.")
    elif english_word == "q":
        # If User wants to quit
        print("Goodbye!")
        break
    else:
        # Word not found
        print(f"Sorry, the translation for '{english_word}' is not available.")

Enter an English word (or 'q' to quit): book
The Spanish translation of 'book' is 'libro'.
Enter an English word (or 'q' to quit): q
Goodbye!


# Lab Task 07

dataset link : https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv
#Exercise
Use the dataset of Game, we have explored earlier and perform following operations.

* Calculate the total global sales for all games in the dataset.
* Find the game with the highest global sales.
* Determine the average sales for each region (NA_Sales, EU_Sales, JP_Sales, Other_Sales).
* Find the top 5 most popular game genres based on global sales.
* Calculate the total sales for each genre in each region and find the most popular genre in North America (NA_Sales).
* Display last 10 rows.
* Determine the top 3 gaming platforms with the highest global sales.
* Calculate the market share (percentage of global sales) for each genre.
* Calculate the correlation coefficient between NA_Sales and EU_Sales. (.corr function)

In [3]:
#  importing wget
import wget
!wget https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv

--2024-02-07 15:37:41--  https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.110.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1355781 (1.3M) [text/plain]
Saving to: ‘vgsalesGlobale.csv’

vgsalesGlobale.csv  100%[===================>]   1.29M  31.6KB/s    in 31s     

2024-02-07 15:38:13 (42.4 KB/s) - ‘vgsalesGlobale.csv’ saved [1355781/1355781]



In [4]:
import pandas as pd

In [7]:
csvfile = "vgsalesGlobale.csv"
df = pd.read_csv(csvfile, index_col="Rank")

In [8]:
df

Name Platform    Year  \
Rank                                                                       
1                                            Wii Sports      Wii  2006.0   
2                                     Super Mario Bros.      NES  1985.0   
3                                        Mario Kart Wii      Wii  2008.0   
4                                     Wii Sports Resort      Wii  2009.0   
5                              Pokemon Red/Pokemon Blue       GB  1996.0   
...                                                 ...      ...     ...   
16596                Woody Woodpecker in Crazy Castle 5      GBA  2002.0   
16597                     Men in Black II: Alien Escape       GC  2003.0   
16598  SCORE International Baja 1000: The Official Game      PS2  2008.0   
16599                                        Know How 2       DS  2010.0   
16600                                  Spirits & Spells      GBA  2003.0   

              Genre   Publisher  NA_Sales  EU_Sales  JP_Sales  Other_Sales  \
Rank                                                                         
1            Sports    Nintendo     41.49     29.02      3.77         8.46   
2          Platform    Nintendo     29.08      3.58      6.81         0.77   
3            Racing    Nintendo     15.85     12.88      3.79         3.31   
4            Sports    Nintendo     15.75     11.01      3.28         2.96   
5      Role-Playing    Nintendo     11.27      8.89     10.22         1.00   
...             ...         ...       ...       ...       ...          ...   
16596      Platform       Kemco      0.01      0.00      0.00         0.00   
16597       Shooter  Infogrames      0.01      0.00      0.00         0.00   
16598        Racing  Activision      0.00      0.00      0.00         0.00   
16599        Puzzle    7G//AMES      0.00      0.01      0.00         0.00   
16600      Platform     Wanadoo      0.01      0.00      0.00         0.00   

       Global_Sales  
Rank                 
1             82.74  
2             40.24  
3             35.82  
4             33.00  
5             31.37  
...             ...  
16596          0.01  
16597          0.01  
16598          0.01  
16599          0.01  
16600          0.01  

[16598 rows x 10 columns]

In [14]:
Total_Global_Sales = df['Global_Sales'].sum()
print(f"Total global sales for all games in the dataset is {Total_Global_Sales}.")

Total global sales for all games in the dataset is 8920.44.


In [15]:
Highest = df['Global_Sales'].max()
print(f"The game with the highest global sales is {Highest}.")

The game with the highest global sales is 82.74.


In [18]:
Avg1 = df['NA_Sales'].mean()
Avg2 = df['EU_Sales'].mean()
Avg3 = df['JP_Sales'].mean()
Avg4 = df['Other_Sales'].mean()

print(f"The average sales for NA_Sales is {round(Avg1, 2)}.")
print(f"The average sales for EU_Sales is {round(Avg2, 2)}.")
print(f"The average sales for JP_Sales is {round(Avg3, 2)}.")
print(f"The average sales for Other_Sales is {round(Avg4, 2)}.")

The average sales for NA_Sales is 0.26.
The average sales for EU_Sales is 0.15.
The average sales for JP_Sales is 0.08.
The average sales for Other_Sales is 0.05.


In [32]:
genre_sales = df.groupby("Genre")["Global_Sales"].sum()

# Sorting genres by total sales in descending order
genre_sales_sorted = genre_sales.sort_values(ascending=False)

# Selecting the top 5 most popular genres
top_5_genres = genre_sales_sorted.head(5)

# Printing the results
print("Top 5 most popular game genres based on global sales:")
for genre, total_sales in top_5_genres.items():
    print(f"* {genre}: {total_sales:.2f}")

Top 5 most popular game genres based on global sales:
* Action: 1751.18
* Sports: 1330.93
* Shooter: 1037.37
* Role-Playing: 927.37
* Platform: 831.37


In [33]:
df.tail(10)

Name Platform    Year  \
Rank                                                                        
16591                                   Mega Brain Boost       DS  2008.0   
16592  Chou Ezaru wa Akai Hana: Koi wa Tsuki ni Shiru...      PSV  2016.0   
16593  Eiyuu Densetsu: Sora no Kiseki Material Collec...      PSP  2007.0   
16594                                Myst IV: Revelation       PC  2004.0   
16595                                           Plushees       DS  2008.0   
16596                 Woody Woodpecker in Crazy Castle 5      GBA  2002.0   
16597                      Men in Black II: Alien Escape       GC  2003.0   
16598   SCORE International Baja 1000: The Official Game      PS2  2008.0   
16599                                         Know How 2       DS  2010.0   
16600                                   Spirits & Spells      GBA  2003.0   

              Genre              Publisher  NA_Sales  EU_Sales  JP_Sales  \
Rank                                                                       
16591        Puzzle  Majesco Entertainment      0.01      0.00      0.00   
16592        Action        dramatic create      0.00      0.00      0.01   
16593  Role-Playing     Falcom Corporation      0.00      0.00      0.01   
16594     Adventure                Ubisoft      0.01      0.00      0.00   
16595    Simulation              Destineer      0.01      0.00      0.00   
16596      Platform                  Kemco      0.01      0.00      0.00   
16597       Shooter             Infogrames      0.01      0.00      0.00   
16598        Racing             Activision      0.00      0.00      0.00   
16599        Puzzle               7G//AMES      0.00      0.01      0.00   
16600      Platform                Wanadoo      0.01      0.00      0.00   

       Other_Sales  Global_Sales  
Rank                              
16591          0.0          0.01  
16592          0.0          0.01  
16593          0.0          0.01  
16594          0.0          0.01  
16595          0.0          0.01  
16596          0.0          0.01  
16597          0.0          0.01  
16598          0.0          0.01  
16599          0.0          0.01  
16600          0.0          0.01

In [35]:
# Group by platform and sum global sales
platform_sales = df.groupby("Platform")["Global_Sales"].sum()

# Sorting platforms by descending global sales
top_3_platforms = platform_sales.sort_values(ascending=False).head(3)

# Printing the results
print("Top 3 platforms with highest global sales:")
for platform, total_sales in top_3_platforms.items():
    print(f"* {platform}: {total_sales:.2f}")

Top 3 platforms with highest global sales:
* PS2: 1255.64
* X360: 979.96
* PS3: 957.84


In [37]:
# Calculating total global sales
total_sales = df["Global_Sales"].sum()

# Calculating market share for each genre
genre_market_share = (df.groupby("Genre")["Global_Sales"].sum() / total_sales) * 100

# Printing the results
print("Market share (percentage of global sales) for each genre:")
for genre, market_share in genre_market_share.items():
    print(f"* {genre}: {market_share:.2f}%")

Market share (percentage of global sales) for each genre:
* Action: 19.63%
* Adventure: 2.68%
* Fighting: 5.03%
* Misc: 9.08%
* Platform: 9.32%
* Puzzle: 2.75%
* Racing: 8.21%
* Role-Playing: 10.40%
* Shooter: 11.63%
* Simulation: 4.40%
* Sports: 14.92%
* Strategy: 1.96%


In [39]:
# Calculating the correlation coefficient
correlation = df["NA_Sales"].corr(df["EU_Sales"])

# Printing the result
print("Correlation coefficient between NA_Sales and EU_Sales:", round(correlation, 2))

Correlation coefficient between NA_Sales and EU_Sales: 0.77
